### PR TITLE
mention that pactree tool should be installed seperately

### PR DESCRIPTION
**Pull request by asmwarrior**

### CODE REVIEW

**Comment by asmwarrior** [comment]
In the page https://wiki.archlinux.org/title/pacman

It is said that: 

> Other useful tools such as [pactree](https://wiki.archlinux.org/title/pacman#Pactree) and [checkupdates](https://wiki.archlinux.org/title/Checkupdates) are found in [pacman-contrib](https://archlinux.org/packages/?name=pacman-contrib) ([formerly](https://gitlab.archlinux.org/pacman/pacman/commit/0c99eabd50752310f42ec808c8734a338122ec86) part of pacman).

**Comment by asmwarrior** [comment]
Sorry, I don't know why I see that "Some checks were not successful", but I just want to improve the wiki page of: [Package Management - MSYS2](https://www.msys2.org/docs/package-management/)

**Comment by Biswa96** [comment]
Would it be better if the `pacman -S pacman-contrib` command is added as first step?

**Comment by asmwarrior** [comment]
> Would it be better if the `pacman -S pacman-contrib` command is added as first step?

You are correct, so let me edit my pull request.

**Comment by asmwarrior** [comment]
Sorry, I don't know how to further edit the changed markdown file on the web. Do I have to clone the branch to my local copy, and change locally, and push the changes? Thanks.

**Comment by Biswa96** [comment]
You can edit the changed markdown file on the web.

**Comment by asmwarrior** [comment]
> You can edit the changed markdown file on the web.

OK, I found it, and now I have committed your suggested changes. Thanks.

**Comment by lazka** [comment]
pacman-contrib is always installed, so I don't understand why this would be needed.

**Comment by asmwarrior** [comment]
> pacman-contrib is always installed, so I don't understand why this would be needed.

I guess that the recent msys2 installer will install the pacman-contrib by default, but old installer won't. In my system, I usually use `pacman -Suy` to update my system, but I don't see the `pactree` command here unless I install the `pacman-contrib` explicitly.

**Comment by lazka** [comment]
That's only possible if you installed before 2020-06: https://www.msys2.org/news/#2020-06-15-new-base-metapackage-pacman-contrib-is-now-separate

You should run `pacman -S base` to fix your installation.

**Comment by asmwarrior** [comment]
> That's only possible if you installed before 2020-06: https://www.msys2.org/news/#2020-06-15-new-base-metapackage-pacman-contrib-is-now-separate
> 
> You should run `pacman -S base` to fix your installation.

Hi, thanks for the reply. I think you are correct. I have checked three PCs of mine. One PC doesn't have `pactree` command installed, the other two PCs have this command installed by default. So, my guess is that the first one PC has quite old msys2 installer(maybe before year 2020), and need to install the command explicitly `pacman -S pacman-contrib` or by using the `pacman -S base` command.

**Comment by lazka** [comment]
Thanks for checking.

Given that this only affects a small (and shrinking) group of users I'd prefer keeping the docs compact over covering all edge cases.

I hope you understand.

**Pull request closed without merging**
