### PR TITLE
Update ides-editors.md to include Visual Studio Code

### PR DESCRIPTION
**Pull request by ZeroAurora**
A copy'n'paste to collect information into one place.

### CODE REVIEW

**Comment by Biswa96** [comment]
Is it possible to use `msys2_shell.cmd` instead of executing bash directly?

**Comment by ZeroAurora** [comment]
@Biswa96 Certainly! but I personally think that starting from bash is more straightforward.

**Comment by Biswa96** [comment]
`msys2_shell.cmd` will allow to change default shell, msys2 environment etc. in one command. Also same command in all docs page may help to understand and migrate different terminal/ide environments.

**Comment by ZeroAurora** [comment]
I updated the doc to use msys2_shell.cmd. I also modified the Sublime example above to use backslash in Windows path.
I want to suggest that when using msys2_shell.cmd to launch the shell, there appears to be a text flash. (The bash appeared, and disappeared, and then appeared again.) But when using bash.exe there is no such problem.
Also, the editor's default configuration seems to execule the shell directly, not through some kind of wrapper.

**Pull request merged**
