### PR TITLE
Add metadata

### PR DESCRIPTION
**Pull request by naveen521kk**
A much-needed one. Also, I may have messed up the summary of pages, please have a look at it.

### CODE REVIEW

**Comment by naveen521kk** [comment]
@lazka Can you review this?

**Comment by lazka** [comment]
What does this change?

**Comment by naveen521kk** [comment]
> What does this change?

when some searches for [msys2 on google](https://www.google.com/search?q=msys2), we see a mingw-64 with its logo. While there should be our own one. That could be done from this PR. See https://developers.google.com/search/docs/data-types/logo for more information.
Also, this has some more additional metadata. Maybe we can add a Twitter card metadata here?

**Comment by lazka** [comment]
ok, you should have linked to https://squidfunk.github.io/mkdocs-material/reference/meta-tags/

**Comment by lazka** [comment]
imo that just complicates things, but ok I guess..

**Comment by naveen521kk** [comment]
> ok, you should have linked to https://squidfunk.github.io/mkdocs-material/reference/meta-tags/

well yeah forgot...

**Comment by naveen521kk** [comment]
@lazka something similar must be done for https://packages.msys2.org

**Pull request merged**
