### PR TITLE
Add Paperwork to the page "Who is Using  MSYS2?"

### PR DESCRIPTION
**Pull request by jflesch**

### CODE REVIEW

**Comment by lazka** [comment]
Thanks!

**Comment by jflesch** [comment]
Well, I'm the one using MSYS2 for my project, so I should be the one telling you thanks ;)

**Comment by mingwandroid** [comment]
Your project looks awesome! Any chance of writing a PKGBUILD for it?

Many thanks for not forgetting about windows users! We use what we must sometimes.

**Comment by Biswa96** [comment]
Many dependencies are not present. Those have to be built first. If we are not out of space in MSYS2 Pacman repo server then I can try to add it.

**Comment by Biswa96** [comment]
Many dependencies are not present. Those have to be built first. If MSYS2 Pacman repo server is not out of space then I can try to add it.

**Pull request merged**
